module.exports = {
	GAME_SETTINGS : {
		GAME_SPEED : {
			SLOW : 0,
			NORMAL : 1,
			FAST : 2
		},
		OBSERVER : {
			OFF : 0,
			UNUSED : 1,
			OBS_ON_DEFEAT : 2,
			ON : 3
		},
		FIXED_TEAMS : {
			OFF : 0,
			UNUSED : 1,
			UNUSED_2 : 2,
			ON : 3
		}
	},
	PLAYER_RECORD : {
		LADDER_GAME : 8
	},
	GAME_TYPE : {
		UNKNOWN : 0,
		LADDER : 1,
		SCENARIO : 1,
		CUSTOM : 9,
		SINGLE_PLAYER : 0x1D,
		LADDER_TEAM : 0x20
	},
	PLAYER_TYPE : {
		GAME_HOST : 0,
		ADDITIONAL_PLAYERS : 0x16
	},
	SLOT_RECORD : {
		SLOT_STATUS : {
			EMPTY : 0x00,
			CLOSED : 0x01,
			USED : 0x02
		},
		COLOR : {
			RED : 0,
			BLUE : 1,
			CYAN : 2,
			PURPLE : 3,
			YELLOW : 4,
			ORANGE : 5,
			GREEN : 6,
			PINK : 7,
			GRAY : 8,
			LIGHT_BLUE : 9,
			DARK_GREEN : 10,
			BROWN : 11,
			OBSERVER : 12
		},
		PLAYER_RACE_FLAGS : {
			HUMAN : 0x01,
			ORC : 0x02,
			NIGHTELF : 0x04,
			UNDEAD : 0x08,
			RANDOM : 0x20,
			RACE_SELECTABLE : 0x40
		},
		COMPUTER_STRENGTH : {
			EASY : 0x00,
			NORMAL : 0x01,
			INSANE : 0x02
		},
	},
	GAME_START_RECORD : {
		SELECT_MODE : {
			TEAM_RACE_SELECTABLE : 0x00,
			TEAM_NOT_SELECTABLE : 0x01,
			TEAM_RACE_NOT_SELECTABLE : 0x03,
			RANDOM_RACE : 0x04,
			AUTOMATED_MATCH_MAKING : 0xCC
		}
	},
	BLOCK_TYPE : {
		LEAVE_GAME : 0x17,
		CHAT : 0x20,
		FIRST : 0x1a,
		SECOND : 0x1b,
		THIRD : 0x1c,
		TIME_SLOT_OLD : 0x1E,
		TIME_SLOT : 0x1F,
		CHECKSUM : 0x22
	},
	CHAT : {
		FLAGS : {
			DELAYED : 0x10,	
			NORMAL : 0x20,
			START : 0x1A
		},
		MODES : {
			ALL: 0x00,
			ALLIES: 0x01,
			OBSERVER: 0x02,
			PLAYER1: 0x03,
			PLAYER2: 0x04,
			PLAYER3: 0x05,
			PLAYER4: 0x06,
			PLAYER5: 0x07,
			PLAYER6: 0x08,
			PLAYER7: 0x09,
			PLAYER8: 0x0A,
			PLAYER9: 0x0B,
			PLAYER10: 0x0C,
			PLAYER11: 0x0D,
			PLAYER12: 0x0E,
		} 
	},
	ACTIONS : {
		PAUSE : 0x01,
		RESUME : 0x02,
		SET_GAME_SPEED : 0x03,
		INCREASE_GAME_SPEED : 0x04,
		DECREASE_GAME_SPEED : 0x05,
		SAVE_GAME : 0x06,
		SAVE_GAME_FINISHED : 0x07,
		UNIT_ABILITY : 0x10,
		UNIT_ABILITY_WITH_POS : 0x11,
		UNIT_ABILITY_WITH_POS_AND_TARGET : 0x12,
		GIVE_DROP_ITEM : 0x13,
		UNIT_ABILITY_2_POS_AND_2_ITEM : 0x14,
		CHANGE_SELECTION : 0x16,
		ASSIGN_GROUP : 0x17,
		SELECT_GROUP : 0x18,
		SELECT_SUBGROUP : 0x19,
		PRE_SUBSELECTION : 0x1A,
		UNKNOWN_0X1B : 0x1B,
		SELECT_GROUND_ITEM : 0x1C,
		CANCEL_HERO_REVIVAL : 0x1D,
		REMOVE_UNIT_FROM_BUILDING_QUEUE : 0x1E,
		UNKNOWN_0X21 : 0X21,
		CHEAT_THE_DUDE_ABIDES : 0X20,
		CHEAT_SOMEBODY_SET_US_UP_THE_BOMB : 0X22,
		CHEAT_WARPTEN : 0X23,
		CHEAT_IOCAINE_POWDER : 0X24,
		CHEAT_POINT_BREAK: 0X25,
		CHEAT_WHOS_YOUR_DADDY : 0X26,
		CHEAT_KEYER_SOZE : 0X27,
		CHEAT_LEAF_IT_TO_ME : 0X28,
		CHEAT_THERE_IS_NO_SPOON : 0X29,
		CHEAT_STRENGTH_AND_HONOR : 0X2A,
		CHEAT_IT_VEXES_ME : 0X2B,
		CHEAT_WHO_IS_JOHN_GALT : 0X2C,
		CHEAT_GREED_IS_GOOD : 0X2D,
		CHEAT_DAYLIGHT_SAVINGS : 0X2E,
		CHEAT_I_SEE_DEAD_PEOPLE : 0X2F,
		CHEAT_SYNERGY : 0X30,
		CHEAT_SHARP_AND_SHINY : 0X31,
		CHEAT_ALL_YOUR_BASE_ARE_BELONG_TO_US : 0X32,
		CHANGE_ALLY_OPTIONS : 0X50,
		TRANSFER_RESOURCES : 0X51,
		MAP_TRIGGER_CHAT_COMMAND : 0X60,
		ESC_PRESSED : 0X61,
		SCENARIO_TRIGGER : 0X62,
		ENTER_CHOOSE_HERO_SKILL_SUBMENU : 0X66,
		ENTER_CHOOSE_BUILDING_SUBMENU : 0X67,
		MINIMAP_SIGNAL : 0X68,
		CONTINUE_GAME_BLOCK_B : 0X69,
		CONTINUE_GAME_BLOCK_A : 0X6A,
		UNKNOWN_0X75 : 0X75,
		SYNC_INTEGER: 0x6B,
		UNKNOWN_0X6D: 0x6D 
	},
	LEAVE_GAME_REASON: {
		CLOSED_BY_REMOTE_GAME: 0x01,
		CLOSED_BY_LOCAL_GAME: 0x0C
	},
	HEADER_SIZE: 48,
	EVENTS: {
		PARSED: {
			HEADER: "parsed-header",
			SUBHEADER: "parsed-sub-header",
			STARTUP_BLOCK: "parsed-startup-block",
			TIME_SLOT: "parsed-time-slot",
			BLOCK: "parsed-block",
			ACTION: "parsed-action",
			CHAT: "parsed-chat",
			LEFT_GAME: "parsed-left-game",
			CHECKSUM: "parsed-checksum"
		},
		ACTIONS: {
			MAP_TRIGGER_CHAT_COMMAND: "map-trigger-chat-command",
			ITEM: "item",
			CHANGE_SELECTION: "change-selection",
			SELECT_GROUP: "select-group",
			UNIT_ABILITY: "unit-ability",
			SELECT_GROUND_ITEM: "select-ground-item",
			UNIT_ABILITY_WITH_POS_AND_TARGET: "unit-ability-with-pos-and-target",
			UNIT_ABILITY_WITH_POS_AND_ITEM: "unit-ability-with-pos-and-item",
			UNIT_ABILITY_WITH_POS: "unit-ability-with-pos",
			UNKNOWN: "unknown",
			GROUP_INFO: "group-info",
			SYNC_INTEGER: "sync-integer",
			SELECT_SUBGROUP: "select-subgroup",
			TRANSFER_RESOURCES: "transfer-resources"
		}
	},
	NULL_STRING: '\0'
}